/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nsmbuniversity;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tharindu dilshan
 */
public class CourseDetail extends javax.swing.JFrame {
   DBOperation dbops=new DBOperation(); 

    UnderGraduateCourseDetail ugcd=new UnderGraduateCourseDetail();
    public CourseDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ddFaculty = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ddCourseId = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ddMainSubject1 = new javax.swing.JComboBox();
        ddMainSubject2 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        ddSubject1 = new javax.swing.JComboBox();
        ddSubject2 = new javax.swing.JComboBox();
        ddSubject3 = new javax.swing.JComboBox();
        ddSubject4 = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ddNumOfYears = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPayment1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtpayment2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPayment3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtpayment4 = new javax.swing.JTextField();
        txtpayment5 = new javax.swing.JTextField();
        txtpayment6 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Course Detail"));

        jLabel1.setText("Faculty");

        ddFaculty.setBackground(new java.awt.Color(102, 153, 255));
        ddFaculty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computing", "Business And Finance", "Engineering" }));
        ddFaculty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddFacultyItemStateChanged(evt);
            }
        });

        jLabel2.setText("Student Id");

        jLabel3.setText("Course Id");

        ddCourseId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cs 1.1", "eng 1.1", "bus 1.1", "cs 1.2", "eng 1.2", "bus 1.2", "cs 2.1", "eng 2.1", "bus2.1", "cs 2.2", "eng 2.2", "bus 2.2", "cs 3.1", "eng 3.1", "bus 3.1", "cs 3.2", "eng 3.2", "bus 3.2", "cs 4.1", "eng 4.1", "bus 4.1", "cs 4.2", "eng 4.2", "bus 4.2" }));
        ddCourseId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddCourseIdItemStateChanged(evt);
            }
        });

        jLabel4.setText("Main Subject 1");

        jLabel5.setText("Main Subject 2");

        jTextField2.setBackground(new java.awt.Color(102, 102, 102));
        jTextField2.setText("Credit 2 Subjects");

        jLabel6.setText("Subject 1");

        jLabel7.setText("Subject 2");

        jLabel8.setText("Subject 3");

        jLabel9.setText("Subject 4");

        ddMainSubject1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddMainSubject2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField3.setBackground(new java.awt.Color(102, 102, 102));
        jTextField3.setText("Credit 3 Subjects");

        ddSubject1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBack.setBackground(new java.awt.Color(255, 51, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel10.setText("Number Of Years");

        ddNumOfYears.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "03", "04" }));

        btnSubmit.setBackground(new java.awt.Color(255, 51, 0));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel11.setText("Add Payment");

        jLabel12.setText("Add Payment");

        jLabel13.setText("Add Payment");

        jLabel14.setText("Add Payment");

        jLabel15.setText("Add Payment");

        jLabel16.setText("Add Payment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel3))
                                    .addGap(1, 1, 1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel6))))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddNumOfYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ddMainSubject1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ddFaculty, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)
                                .addComponent(ddCourseId, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ddMainSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPayment1)
                            .addComponent(txtpayment2)
                            .addComponent(txtPayment3)
                            .addComponent(txtpayment4)
                            .addComponent(txtpayment5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(txtpayment6))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ddCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ddNumOfYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddMainSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(txtPayment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ddMainSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtpayment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ddSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtPayment3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ddSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtpayment4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ddSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtpayment5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ddSubject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtpayment6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
    
    
    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        UnderGraduateCourseDetail ugc=new UnderGraduateCourseDetail();
        
        int x=dbops.checkStudentId3(txtStudentId.getText(),ddCourseId.getSelectedItem().toString());
        
        if(x==1){
            ugc.setFaculty(ddFaculty.getSelectedItem().toString());
        ugc.setStudentId(Integer.parseInt(txtStudentId.getText()));
        ugc.setCourseId((String) (ddCourseId.getSelectedItem()));
        ugc.setNumOfYears(Integer.parseInt(ddNumOfYears.getSelectedItem().toString()));
        ugc.setMainSubject1(ddMainSubject1.getSelectedItem().toString());
        ugc.setMainSubject2(ddMainSubject2.getSelectedItem().toString());
        ugc.setSubject1(ddSubject1.getSelectedItem().toString());
        ugc.setSubject2(ddSubject2.getSelectedItem().toString());
        ugc.setSubject3(ddSubject3.getSelectedItem().toString());
        ugc.setSubject4(ddSubject4.getSelectedItem().toString());
        ugc.setMain1payment(Integer.parseInt(txtPayment1.getText()));
        ugc.setMain2payment(Integer.parseInt(txtpayment2.getText()));
        ugc.setSub1payment(Integer.parseInt(txtPayment3.getText()));
        ugc.setSub2payment(Integer.parseInt(txtpayment4.getText()));
        ugc.setSub3payment(Integer.parseInt(txtpayment5.getText()));
        ugc.setSub4payment(Integer.parseInt(txtpayment6.getText()));
        
        dbops.underGraduateCourse(ugc);
        JOptionPane.showMessageDialog(this, "Successfull entered");
        txtStudentId.setText("");
        }
        
        else if(x==0){
            JOptionPane.showMessageDialog(this, "student id and course id already exist");
           txtStudentId.setText("");
        }
        else{
            JOptionPane.showMessageDialog(this, "error occured");
        }
        
       
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void ddCourseIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddCourseIdItemStateChanged
        
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddMainSubject1.setModel(new DefaultComboBoxModel(this.getmainsubject1(this.ddCourseId.getSelectedItem().toString())));
            }
        }
        
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddMainSubject2.setModel(new DefaultComboBoxModel(this.getmainsubject2(this.ddCourseId.getSelectedItem().toString())));
            }
        }
        
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject1.setModel(new DefaultComboBoxModel(this.getsubject1(this.ddCourseId.getSelectedItem().toString())));
            }
        }
        
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject2.setModel(new DefaultComboBoxModel(this.getsubject2(this.ddCourseId.getSelectedItem().toString())));
            }
        }
        
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject3.setModel(new DefaultComboBoxModel(this.getsubject3(this.ddCourseId.getSelectedItem().toString())));
            }
        }
        
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject4.setModel(new DefaultComboBoxModel(this.getsubject4(this.ddCourseId.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_ddCourseIdItemStateChanged

    private void ddFacultyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddFacultyItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddFaculty.getSelectedIndex()>=0){
                this.ddCourseId.setModel(new DefaultComboBoxModel(this.getcourseid(this.ddFaculty.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_ddFacultyItemStateChanged
    
   public String[] getcourseid(String pais){
       String[] courseid=new String[8];
       if(pais.equalsIgnoreCase("Computing")){
       courseid[0]="cs 1.1";
       courseid[1]="cs 1.2";
       courseid[2]="cs 2.1";
       courseid[3]="cs 2.2";
       courseid[4]="cs 3.1";
       courseid[5]="cs 3.2";
       courseid[6]="cs 4.1";
       courseid[7]="cs 4.2";
       }
       
        if(pais.equalsIgnoreCase("Business And Finance")){
       courseid[0]="bus 1.1";
       courseid[1]="bus 1.2";
       courseid[2]="bus 2.1";
       courseid[3]="bus 2.2";
       courseid[4]="bus 3.1";
       courseid[5]="bus 3.2";
       courseid[6]="bus 4.1";
       courseid[7]="bus 4.2";
       }
       
       if(pais.equalsIgnoreCase("Engineering")){
       courseid[0]="eng 1.1";
       courseid[1]="eng 1.2";
       courseid[2]="eng 2.1";
       courseid[3]="eng 2.2";
       courseid[4]="eng 3.1";
       courseid[5]="eng 3.2";
       courseid[6]="eng 4.1";
       courseid[7]="eng 4.2";
       }
       
       return courseid; 
   
   } 
   public String[] getmainsubject1(String pais){
        String[] mainsubject1=new String[2];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Calculus";
            
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="Management Theory and Practice";
           
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="ICT Tools";
           
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Environment and Energy Studies";
           
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Management of Change";
           
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Computer Security (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Community Services";
          
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Research Methods";
           
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            
            mainsubject1[0]="Software Testing and Quality Assurance (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            
            mainsubject1[0]="Heat and Mass Transfer";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           
            mainsubject1[0]="Management of Change";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
           
            mainsubject1[0]="Project Part- I";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Law for Engineers";
            
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
            mainsubject1[0]="Current Developments in Accounting Thought";
           
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
            mainsubject1[0]="Compiler Design";
           
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
            mainsubject1[0]="Thermal Engineering";
           
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
           
            mainsubject1[0]="Investments Analysis";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="Cyber Security";
           
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
          
            mainsubject1[0]="Control Engineering";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
            mainsubject1[0]="Management of Change";
         
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
           
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Heat and Mass Transfer";
           
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="Human Resource Management";
            
        } 
          return mainsubject1;
              
    }
   
    public String[] getmainsubject2(String pais){
        String[] mainsubject1=new String[1];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="ICT Tools";
            
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Heat and Mass Transfer";
            
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="Human Resource Management";
           
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="Cyber Security";
           
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Ethics & Values";
           
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Current Developments in Accounting Thought";
           
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Cyber Security";
            
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Community Services";
           
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Current Developments in Accounting Thought";
             
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            
            mainsubject1[0]="Data Structure and Algorithms";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
           
            mainsubject1[0]="Control Engineering";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           
            mainsubject1[0]="Marketing Management";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
          
            mainsubject1[0]="Project Part- I";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
           
            mainsubject1[1]="Heat and Mass Transfer";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
            mainsubject1[0]="Business Economics";
           
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
            mainsubject1[0]="Electrical Workshop Practices";
           
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
           
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="High Speed Networks";
           
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
              mainsubject1[0]="Community Services";
           
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
            mainsubject1[0]="Computer Security (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Mechanical Workshop Practices";
            
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="Taxation 1";
           
        } 
          return mainsubject1;
              
    }
    
    public String[] getsubject1(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="Data Structure and Algorithms";
            mainsubject1[1]="ICT Tools";
            mainsubject1[2]="Database Systems";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Physics";
            mainsubject1[1]="Kinematics";
            mainsubject1[2]="Mechanics of Solids";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
           mainsubject1[0]="Taxation 1";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="IT Risk Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="ICT Tools";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Law for Engineers";
            mainsubject1[1]="Capston Course (Mechanical Engineering)";
            mainsubject1[2]="Yog and Meditation";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Organisational Behaviour";
            mainsubject1[1]="IT Management Issues";
            mainsubject1[2]="Integrated Marketing Communications";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Computer Architecture";
            mainsubject1[1]="Software Engineering";
            mainsubject1[2]="Data Warehousing and Mining (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
           mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Corporate Finance";
            mainsubject1[2]="Financial Planning";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
     public String[] getsubject2(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
             mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
           mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
              mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
           mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
             mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
               mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
           mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Corporate Finance";
            mainsubject1[2]="Financial Planning";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
    public String[] getsubject3(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="ICT Tools";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
             mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Organisational Behaviour";
            mainsubject1[1]="IT Management Issues";
            mainsubject1[2]="Integrated Marketing Communications";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Computer Architecture";
            mainsubject1[1]="Software Engineering";
            mainsubject1[2]="Data Warehousing and Mining (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
           mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Corporate Finance";
            mainsubject1[2]="Financial Planning";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
    public String[] getsubject4(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
           mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)"; 
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management"; 
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
               mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
        
          if(pais.equalsIgnoreCase("bus 2.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
               mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
              mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management"; 
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
               mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
           mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
             mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
             mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    /*
    *
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox ddCourseId;
    private javax.swing.JComboBox ddFaculty;
    private javax.swing.JComboBox ddMainSubject1;
    private javax.swing.JComboBox ddMainSubject2;
    private javax.swing.JComboBox ddNumOfYears;
    private javax.swing.JComboBox ddSubject1;
    private javax.swing.JComboBox ddSubject2;
    private javax.swing.JComboBox ddSubject3;
    private javax.swing.JComboBox ddSubject4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtPayment1;
    private javax.swing.JTextField txtPayment3;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtpayment2;
    private javax.swing.JTextField txtpayment4;
    private javax.swing.JTextField txtpayment5;
    private javax.swing.JTextField txtpayment6;
    // End of variables declaration//GEN-END:variables

    //To change body of generated methods, choose Tools | Templates.
    

   
}
