/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsmbuniversity;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tharindu dilshan
 */
public class InstructorSubjectl extends javax.swing.JFrame {
    DBOperation dbops=new DBOperation();
    /**
     * Creates new form InstructorSubjectl
     */
    public InstructorSubjectl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtInstructorId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ddFaculty = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        ddCourseId = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ddMainSubject1 = new javax.swing.JComboBox();
        ddMainSubject2 = new javax.swing.JComboBox();
        ddSubject1 = new javax.swing.JComboBox();
        ddSubject2 = new javax.swing.JComboBox();
        ddSubject3 = new javax.swing.JComboBox();
        ddSubject4 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ddFaculty1 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        ddCourseId1 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ddMainSubject3 = new javax.swing.JComboBox();
        ddMainSubject4 = new javax.swing.JComboBox();
        ddSubject5 = new javax.swing.JComboBox();
        ddSubject6 = new javax.swing.JComboBox();
        ddSubject7 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Add Lectuers Subjects");

        jLabel2.setBackground(new java.awt.Color(13, 13, 216));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsmbuniversity/subject-clipart-dcrabBgc8.jpg"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(117, 117, 204));

        jLabel3.setText("Instructor Id");

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Under Graduate");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Faculty");

        ddFaculty.setBackground(new java.awt.Color(153, 153, 153));
        ddFaculty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computing", "Business And Finance", "Engineering" }));
        ddFaculty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddFacultyItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Course Id");

        ddCourseId.setBackground(new java.awt.Color(153, 153, 153));
        ddCourseId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cs 1.1", "eng 1.1", "bus 1.1", "cs 1.2", "eng 1.2", "bus 1.2", "cs 2.1", "eng 2.1", "bus2.1", "cs 2.2", "eng 2.2", "bus 2.2", "cs 3.1", "eng 3.1", "bus 3.1", "cs 3.2", "eng 3.2", "bus 3.2", "cs 4.1", "eng 4.1", "bus 4.1", "cs 4.2", "eng 4.2", "bus 4.2" }));
        ddCourseId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddCourseIdItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Main Subject 1");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Main Subject 2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Subject 1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Subject 2");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Subject 3");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Subject 4");

        ddMainSubject1.setBackground(new java.awt.Color(153, 153, 153));
        ddMainSubject1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddMainSubject2.setBackground(new java.awt.Color(153, 153, 153));
        ddMainSubject2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject1.setBackground(new java.awt.Color(153, 153, 153));
        ddSubject1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject2.setBackground(new java.awt.Color(153, 153, 153));
        ddSubject2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject3.setBackground(new java.awt.Color(153, 153, 153));
        ddSubject3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject4.setBackground(new java.awt.Color(153, 153, 153));
        ddSubject4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel7))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddMainSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddMainSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ddCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ddMainSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(ddMainSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(ddSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(ddSubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(ddSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ddSubject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Post Graduate");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Faculty");

        ddFaculty1.setBackground(new java.awt.Color(153, 153, 153));
        ddFaculty1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computing", "Business And Finance", "Engineering" }));
        ddFaculty1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddFaculty1ItemStateChanged(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Course Id");

        ddCourseId1.setBackground(new java.awt.Color(153, 153, 153));
        ddCourseId1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cs 1.1", "eng 1.1", "bus 1.1", "cs 1.2", "eng 1.2", "bus 1.2", "cs 2.1", "eng 2.1", "bus2.1", "cs 2.2", "eng 2.2", "bus 2.2", "cs 3.1", "eng 3.1", "bus 3.1", "cs 3.2", "eng 3.2", "bus 3.2", "cs 4.1", "eng 4.1", "bus 4.1", "cs 4.2", "eng 4.2", "bus 4.2" }));
        ddCourseId1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddCourseId1ItemStateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Main Subject 1");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Main Subject 2");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Subject 1");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Subject 2");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Subject 3");

        ddMainSubject3.setBackground(new java.awt.Color(153, 153, 153));
        ddMainSubject3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddMainSubject4.setBackground(new java.awt.Color(153, 153, 153));
        ddMainSubject4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject5.setBackground(new java.awt.Color(153, 153, 153));
        ddSubject5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject6.setBackground(new java.awt.Color(153, 153, 153));
        ddSubject6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ddSubject7.setBackground(new java.awt.Color(153, 153, 153));
        ddSubject7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel17))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel16))
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ddFaculty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddCourseId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddMainSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddMainSubject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubject7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel14)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(ddFaculty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ddCourseId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(ddMainSubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(ddMainSubject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(ddSubject5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(ddSubject6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(ddSubject7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50)
                        .addComponent(txtInstructorId, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInstructorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addGap(21, 21, 21)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ddFacultyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddFacultyItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddFaculty.getSelectedIndex()>=0){
                this.ddCourseId.setModel(new DefaultComboBoxModel(this.getcourseid(this.ddFaculty.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_ddFacultyItemStateChanged
    
    public String[] getcourseid(String pais){
       String[] courseid=new String[8];
       if(pais.equalsIgnoreCase("Computing")){
       courseid[0]="cs 1.1";
       courseid[1]="cs 1.2";
       courseid[2]="cs 2.1";
       courseid[3]="cs 2.2";
       courseid[4]="cs 3.1";
       courseid[5]="cs 3.2";
       courseid[6]="cs 4.1";
       courseid[7]="cs 4.2";
       }
       
        if(pais.equalsIgnoreCase("Business And Finance")){
       courseid[0]="bus 1.1";
       courseid[1]="bus 1.2";
       courseid[2]="bus 2.1";
       courseid[3]="bus 2.2";
       courseid[4]="bus 3.1";
       courseid[5]="bus 3.2";
       courseid[6]="bus 4.1";
       courseid[7]="bus 4.2";
       }
       
       if(pais.equalsIgnoreCase("Engineering")){
       courseid[0]="eng 1.1";
       courseid[1]="eng 1.2";
       courseid[2]="eng 2.1";
       courseid[3]="eng 2.2";
       courseid[4]="eng 3.1";
       courseid[5]="eng 3.2";
       courseid[6]="eng 4.1";
       courseid[7]="eng 4.2";
       }
       
       return courseid; 
   
   }
    
    
    
   
    
    
    private void ddCourseIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddCourseIdItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddMainSubject1.setModel(new DefaultComboBoxModel(this.getmainsubject1(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddMainSubject2.setModel(new DefaultComboBoxModel(this.getmainsubject2(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject1.setModel(new DefaultComboBoxModel(this.getsubject1(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject2.setModel(new DefaultComboBoxModel(this.getsubject2(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject3.setModel(new DefaultComboBoxModel(this.getsubject3(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId.getSelectedIndex()>=0){
                this.ddSubject4.setModel(new DefaultComboBoxModel(this.getsubject4(this.ddCourseId.getSelectedItem().toString())));
            }
        }

    }//GEN-LAST:event_ddCourseIdItemStateChanged
    
    public String[] getmainsubject1(String pais){
        String[] mainsubject1=new String[2];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Calculus";
            
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="Management Theory and Practice";
           
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="ICT Tools";
           
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Environment and Energy Studies";
           
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Management of Change";
           
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Computer Security (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Community Services";
          
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Research Methods";
           
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            
            mainsubject1[0]="Software Testing and Quality Assurance (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            
            mainsubject1[0]="Heat and Mass Transfer";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           
            mainsubject1[0]="Management of Change";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
           
            mainsubject1[0]="Project Part- I";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Law for Engineers";
            
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
            mainsubject1[0]="Current Developments in Accounting Thought";
           
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
            mainsubject1[0]="Compiler Design";
           
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
            mainsubject1[0]="Thermal Engineering";
           
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
           
            mainsubject1[0]="Investments Analysis";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="Cyber Security";
           
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
          
            mainsubject1[0]="Control Engineering";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
            mainsubject1[0]="Management of Change";
         
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
           
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Heat and Mass Transfer";
           
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="Human Resource Management";
            
        } 
          return mainsubject1;
              
    }
   
    public String[] getmainsubject2(String pais){
        String[] mainsubject1=new String[1];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="ICT Tools";
            
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Heat and Mass Transfer";
            
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="Human Resource Management";
           
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="Cyber Security";
           
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Ethics & Values";
           
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Current Developments in Accounting Thought";
           
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Cyber Security";
            
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Community Services";
           
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Current Developments in Accounting Thought";
             
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            
            mainsubject1[0]="Data Structure and Algorithms";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
           
            mainsubject1[0]="Control Engineering";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           
            mainsubject1[0]="Marketing Management";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
          
            mainsubject1[0]="Project Part- I";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
           
            mainsubject1[1]="Heat and Mass Transfer";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
            mainsubject1[0]="Business Economics";
           
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
            mainsubject1[0]="Electrical Workshop Practices";
           
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
           
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="High Speed Networks";
           
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
              mainsubject1[0]="Community Services";
           
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
            mainsubject1[0]="Computer Security (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Mechanical Workshop Practices";
            
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="Taxation 1";
           
        } 
          return mainsubject1;
              
    }
    
    public String[] getsubject1(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="Data Structure and Algorithms";
            mainsubject1[1]="ICT Tools";
            mainsubject1[2]="Database Systems";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Physics";
            mainsubject1[1]="Kinematics";
            mainsubject1[2]="Mechanics of Solids";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
           mainsubject1[0]="Taxation 1";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="IT Risk Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="ICT Tools";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Law for Engineers";
            mainsubject1[1]="Capston Course (Mechanical Engineering)";
            mainsubject1[2]="Yog and Meditation";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Organisational Behaviour";
            mainsubject1[1]="IT Management Issues";
            mainsubject1[2]="Integrated Marketing Communications";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Computer Architecture";
            mainsubject1[1]="Software Engineering";
            mainsubject1[2]="Data Warehousing and Mining (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
           mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Corporate Finance";
            mainsubject1[2]="Financial Planning";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
     public String[] getsubject2(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
             mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
           mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
              mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
           mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
             mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
               mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
           mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Corporate Finance";
            mainsubject1[2]="Financial Planning";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
    public String[] getsubject3(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="ICT Tools";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
             mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Organisational Behaviour";
            mainsubject1[1]="IT Management Issues";
            mainsubject1[2]="Integrated Marketing Communications";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Computer Architecture";
            mainsubject1[1]="Software Engineering";
            mainsubject1[2]="Data Warehousing and Mining (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
           mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Corporate Finance";
            mainsubject1[2]="Financial Planning";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
    public String[] getsubject4(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
           mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)"; 
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management"; 
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
               mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
        
          if(pais.equalsIgnoreCase("bus 2.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
               mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
              mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management"; 
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
               mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
           mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
             mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
             mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
    public String[] getmainsubject3(String pais){
        String[] mainsubject1=new String[2];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Calculus";
            
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="Management Theory and Practice";
           
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="ICT Tools";
           
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Environment and Energy Studies";
           
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Management of Change";
           
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Computer Security (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Community Services";
          
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Research Methods";
           
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            
            mainsubject1[0]="Software Testing and Quality Assurance (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            
            mainsubject1[0]="Heat and Mass Transfer";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           
            mainsubject1[0]="Management of Change";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
           
            mainsubject1[0]="Project Part- I";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Law for Engineers";
            
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
            mainsubject1[0]="Current Developments in Accounting Thought";
           
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
            mainsubject1[0]="Compiler Design";
           
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
            mainsubject1[0]="Thermal Engineering";
           
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
           
            mainsubject1[0]="Investments Analysis";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="Cyber Security";
           
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
          
            mainsubject1[0]="Control Engineering";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
            mainsubject1[0]="Management of Change";
         
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
           
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Heat and Mass Transfer";
           
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="Human Resource Management";
            
        } 
          return mainsubject1;
              
    }
   
    public String[] getmainsubject4(String pais){
        String[] mainsubject1=new String[1];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="ICT Tools";
            
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Heat and Mass Transfer";
            
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="Human Resource Management";
           
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="Cyber Security";
           
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Ethics & Values";
           
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Current Developments in Accounting Thought";
           
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Cyber Security";
            
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Community Services";
           
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Current Developments in Accounting Thought";
             
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            
            mainsubject1[0]="Data Structure and Algorithms";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
           
            mainsubject1[0]="Control Engineering";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           
            mainsubject1[0]="Marketing Management";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
          
            mainsubject1[0]="Project Part- I";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
           
            mainsubject1[1]="Heat and Mass Transfer";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
            mainsubject1[0]="Business Economics";
           
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
            mainsubject1[0]="Electrical Workshop Practices";
           
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
           
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="High Speed Networks";
           
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
              mainsubject1[0]="Community Services";
           
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
            mainsubject1[0]="Computer Security (Elective)";
            
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Mechanical Workshop Practices";
            
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="Taxation 1";
           
        } 
          return mainsubject1;
              
    }
    
    public String[] getsubject5(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="Data Structure and Algorithms";
            mainsubject1[1]="ICT Tools";
            mainsubject1[2]="Database Systems";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Physics";
            mainsubject1[1]="Kinematics";
            mainsubject1[2]="Mechanics of Solids";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
           mainsubject1[0]="Taxation 1";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="IT Risk Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="ICT Tools";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Law for Engineers";
            mainsubject1[1]="Capston Course (Mechanical Engineering)";
            mainsubject1[2]="Yog and Meditation";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Organisational Behaviour";
            mainsubject1[1]="IT Management Issues";
            mainsubject1[2]="Integrated Marketing Communications";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Computer Architecture";
            mainsubject1[1]="Software Engineering";
            mainsubject1[2]="Data Warehousing and Mining (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
           mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Corporate Finance";
            mainsubject1[2]="Financial Planning";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
     public String[] getsubject6(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
             mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
           mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
              mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
            mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
           mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
             mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
               mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
           mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Corporate Finance";
            mainsubject1[2]="Financial Planning";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
    public String[] getsubject7(String pais){
        String[] mainsubject1=new String[3];
        if(pais.equalsIgnoreCase("cs 1.1")){
            mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="ICT Tools";
        }
        if(pais.equalsIgnoreCase("eng 1.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
        
         if(pais.equalsIgnoreCase("bus 1.1")){
             mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        }
          if(pais.equalsIgnoreCase("cs 1.2")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 1.2")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 1.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Strategic Human Resource Development";
        }
          if(pais.equalsIgnoreCase("cs 2.1")){
            mainsubject1[0]="Artificial Intelligence (Elective)";
            mainsubject1[1]="Distributed and Parallel Systems";
            mainsubject1[2]="High Speed Networks";
        }
          if(pais.equalsIgnoreCase("eng 2.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Critical Thinking";
        }
          if(pais.equalsIgnoreCase("bus 2.1")){
            mainsubject1[0]="Organisational Behaviour";
            mainsubject1[1]="IT Management Issues";
            mainsubject1[2]="Integrated Marketing Communications";
        }
          if(pais.equalsIgnoreCase("cs 2.2")){
            mainsubject1[0]="Computer Architecture";
            mainsubject1[1]="Software Engineering";
            mainsubject1[2]="Data Warehousing and Mining (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 2.2")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="English - Foreign Language";
        }
          if(pais.equalsIgnoreCase("bus 2.2")){
           mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Management of Change";
            mainsubject1[2]="Taxation 1";
        }   
          if(pais.equalsIgnoreCase("cs 3.1")){
            mainsubject1[0]="Cyber Security";
            mainsubject1[1]="Project Part- I";
            mainsubject1[2]="Practical Training";
        }
          if(pais.equalsIgnoreCase("eng 3.1")){
            mainsubject1[0]="Thermal Engineering";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Engineering Graphics";
        }
          if(pais.equalsIgnoreCase("bus 3.1")){
           mainsubject1[0]="Current Developments in Accounting Thought";
            mainsubject1[1]="Investments Analysis";
            mainsubject1[2]="ICT Project Management";
        }
          if(pais.equalsIgnoreCase("cs 3.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Comprehensive Assessment - II";
        }
          if(pais.equalsIgnoreCase("eng 3.2")){
             mainsubject1[0]="Mini Project – II";
            mainsubject1[1]="Control Engineering";
            mainsubject1[2]="Elements of Electrical Engineering";
        }
          if(pais.equalsIgnoreCase("bus 3.2")){
            mainsubject1[0]="Management of Change";
            mainsubject1[1]="Marketing Management";
            mainsubject1[2]="Advanced Studies in industrial Relations";
        }
          if(pais.equalsIgnoreCase("cs 4.1")){
            mainsubject1[0]="ICT Tools";
            mainsubject1[1]="Software Testing and Quality Assurance (Elective)";
            mainsubject1[2]="Modern Databases (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.1")){
            mainsubject1[0]="Linear Algebra";
            mainsubject1[1]="Engineering Graphics";
            mainsubject1[2]="Ethics & Values";
        }
          if(pais.equalsIgnoreCase("bus 4.1")){
             mainsubject1[0]="Human Resource Management";
            mainsubject1[1]="Corporate Finance";
            mainsubject1[2]="Financial Planning";
        }
          if(pais.equalsIgnoreCase("cs 4.2")){
             mainsubject1[0]="High Speed Networks";
            mainsubject1[1]="Data Structure and Algorithms";
            mainsubject1[2]="Cloud Computing (Elective)";
        }
          if(pais.equalsIgnoreCase("eng 4.2")){
            mainsubject1[0]="Ethics & Values";
            mainsubject1[1]="Thermodynamics";
            mainsubject1[2]="Dynamics of Machinery I";
        }
          if(pais.equalsIgnoreCase("bus 4.2")){
            mainsubject1[0]="International Human Resource Management";
            mainsubject1[1]="Business and Corporations Law";
            mainsubject1[2]="Marketing Management";
        } 
          return mainsubject1;
              
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddLecturerSubject als=new AddLecturerSubject();

        als.setLecturerId(Integer.parseInt(txtInstructorId.getText()));
        als.setFaculty(ddFaculty.getSelectedItem().toString());
        als.setCourseId(ddCourseId.getSelectedItem().toString());
        als.setMainSubject1(ddMainSubject1.getSelectedItem().toString());
        als.setMainsubject2(ddMainSubject2.getSelectedItem().toString());
        als.setSubject1(ddSubject1.getSelectedItem().toString());
        als.setSubject2(ddSubject2.getSelectedItem().toString());
        als.setSubject3(ddSubject3.getSelectedItem().toString());
        als.setSubject4(ddSubject4.getSelectedItem().toString());

        dbops.InstructorUnderGraduateSubject(als);
        JOptionPane.showMessageDialog(this, "successfull");
        txtInstructorId.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ddFaculty1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddFaculty1ItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddFaculty1.getSelectedIndex()>=0){
                this.ddCourseId1.setModel(new DefaultComboBoxModel(this.getcourseid1(this.ddFaculty1.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_ddFaculty1ItemStateChanged

    
    public String[] getcourseid1(String pais){
       String[] courseid=new String[8];
       if(pais.equalsIgnoreCase("Computing")){
       courseid[0]="cs 1.1";
       courseid[1]="cs 1.2";
       courseid[2]="cs 2.1";
       courseid[3]="cs 2.2";
       courseid[4]="cs 3.1";
       courseid[5]="cs 3.2";
       courseid[6]="cs 4.1";
       courseid[7]="cs 4.2";
       }
       
        if(pais.equalsIgnoreCase("Business And Finance")){
       courseid[0]="bus 1.1";
       courseid[1]="bus 1.2";
       courseid[2]="bus 2.1";
       courseid[3]="bus 2.2";
       courseid[4]="bus 3.1";
       courseid[5]="bus 3.2";
       courseid[6]="bus 4.1";
       courseid[7]="bus 4.2";
       }
       
       if(pais.equalsIgnoreCase("Engineering")){
       courseid[0]="eng 1.1";
       courseid[1]="eng 1.2";
       courseid[2]="eng 2.1";
       courseid[3]="eng 2.2";
       courseid[4]="eng 3.1";
       courseid[5]="eng 3.2";
       courseid[6]="eng 4.1";
       courseid[7]="eng 4.2";
       }
       
       return courseid; 
   
   }
    private void ddCourseId1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddCourseId1ItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId1.getSelectedIndex()>=0){
                this.ddMainSubject3.setModel(new DefaultComboBoxModel(this.getmainsubject3(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId1.getSelectedIndex()>=0){
                this.ddMainSubject4.setModel(new DefaultComboBoxModel(this.getmainsubject4(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId1.getSelectedIndex()>=0){
                this.ddSubject5.setModel(new DefaultComboBoxModel(this.getsubject5(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId1.getSelectedIndex()>=0){
                this.ddSubject6.setModel(new DefaultComboBoxModel(this.getsubject6(this.ddCourseId.getSelectedItem().toString())));
            }
        }

        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.ddCourseId1.getSelectedIndex()>=0){
                this.ddSubject7.setModel(new DefaultComboBoxModel(this.getsubject7(this.ddCourseId.getSelectedItem().toString())));
            }
        }

    }//GEN-LAST:event_ddCourseId1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddLecturerSubject al=new AddLecturerSubject();

        al.setLecturerId(Integer.parseInt(txtInstructorId.getText()));
        al.setFaculty(ddFaculty1.getSelectedItem().toString());
        al.setCourseId(ddCourseId1.getSelectedItem().toString());
        al.setMainSubject1(ddMainSubject3.getSelectedItem().toString());
        al.setMainsubject2(ddMainSubject4.getSelectedItem().toString());
        al.setSubject1(ddSubject5.getSelectedItem().toString());
        al.setSubject2(ddSubject6.getSelectedItem().toString());
        al.setSubject3(ddSubject7.getSelectedItem().toString());

        dbops.InstructorPostGraduateSubject(al);
        JOptionPane.showMessageDialog(this, "successful");
        txtInstructorId.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorSubjectl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorSubjectl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorSubjectl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorSubjectl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorSubjectl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ddCourseId;
    private javax.swing.JComboBox ddCourseId1;
    private javax.swing.JComboBox ddFaculty;
    private javax.swing.JComboBox ddFaculty1;
    private javax.swing.JComboBox ddMainSubject1;
    private javax.swing.JComboBox ddMainSubject2;
    private javax.swing.JComboBox ddMainSubject3;
    private javax.swing.JComboBox ddMainSubject4;
    private javax.swing.JComboBox ddSubject1;
    private javax.swing.JComboBox ddSubject2;
    private javax.swing.JComboBox ddSubject3;
    private javax.swing.JComboBox ddSubject4;
    private javax.swing.JComboBox ddSubject5;
    private javax.swing.JComboBox ddSubject6;
    private javax.swing.JComboBox ddSubject7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtInstructorId;
    // End of variables declaration//GEN-END:variables
}
