/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nsmbuniversity;

import java.util.ArrayList;

/**
 *
 * @author Tharindu dilshan
 */
public class MainFrame extends javax.swing.JFrame {

    
    public MainFrame() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnAddUnderGraduateStudent = new javax.swing.JButton();
        btnUnderGraduateCourse = new javax.swing.JButton();
        btnUnderGraduateResult = new javax.swing.JButton();
        btnCalGPA = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnAddLectures = new javax.swing.JButton();
        btnAddInstrucrors = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        AddLectures1 = new javax.swing.JButton();
        btnAddInstructors = new javax.swing.JButton();
        btnLecturessujects = new javax.swing.JButton();
        btnInstructorsSubjects = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAddPostGraduateStudent = new javax.swing.JButton();
        btnPostGraduateCourse = new javax.swing.JButton();
        btnPostGraduateResult = new javax.swing.JButton();
        btnPostCalGPA = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 142, 204));

        jLabel1.setBackground(new java.awt.Color(50, 137, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("  NSBM University");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enrollment System");

        jPanel3.setBackground(new java.awt.Color(50, 75, 255));

        btnAddUnderGraduateStudent.setBackground(new java.awt.Color(102, 102, 102));
        btnAddUnderGraduateStudent.setText("Add Student");
        btnAddUnderGraduateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUnderGraduateStudentActionPerformed(evt);
            }
        });

        btnUnderGraduateCourse.setBackground(new java.awt.Color(102, 102, 102));
        btnUnderGraduateCourse.setText("Add Course");
        btnUnderGraduateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnderGraduateCourseActionPerformed(evt);
            }
        });

        btnUnderGraduateResult.setBackground(new java.awt.Color(102, 102, 102));
        btnUnderGraduateResult.setText("Set Result");
        btnUnderGraduateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnderGraduateResultActionPerformed(evt);
            }
        });

        btnCalGPA.setBackground(new java.awt.Color(102, 102, 102));
        btnCalGPA.setText("Calculate GPA");
        btnCalGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalGPAActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Update And Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsmbuniversity/td.jpg"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Update And Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("Update And Delete");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnAddUnderGraduateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnUnderGraduateCourse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(btnUnderGraduateResult, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnCalGPA))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton2)
                                .addGap(40, 40, 40)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUnderGraduateStudent)
                    .addComponent(btnUnderGraduateCourse)
                    .addComponent(btnCalGPA)
                    .addComponent(btnUnderGraduateResult))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Under Graduate", jPanel3);

        jPanel4.setBackground(new java.awt.Color(163, 98, 206));

        btnAddLectures.setBackground(new java.awt.Color(153, 153, 153));
        btnAddLectures.setText("Add Lectures");
        btnAddLectures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLecturesActionPerformed(evt);
            }
        });

        btnAddInstrucrors.setBackground(new java.awt.Color(153, 153, 153));
        btnAddInstrucrors.setText("Add Instructors");
        btnAddInstrucrors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInstrucrorsActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsmbuniversity/kk.jpg"))); // NOI18N

        AddLectures1.setBackground(new java.awt.Color(153, 153, 153));
        AddLectures1.setText("Add Lectures");
        AddLectures1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLectures1ActionPerformed(evt);
            }
        });

        btnAddInstructors.setBackground(new java.awt.Color(153, 153, 153));
        btnAddInstructors.setText("Add Instructors");
        btnAddInstructors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInstructorsActionPerformed(evt);
            }
        });

        btnLecturessujects.setBackground(new java.awt.Color(153, 153, 153));
        btnLecturessujects.setText("Lectures Subjects");
        btnLecturessujects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturessujectsActionPerformed(evt);
            }
        });

        btnInstructorsSubjects.setBackground(new java.awt.Color(153, 153, 153));
        btnInstructorsSubjects.setText("Instructors Subjects");
        btnInstructorsSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructorsSubjectsActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("Update And Delete");

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setText("Update And Delete");

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setText("Update And Delete");

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setText("Update And Delete");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(AddLectures1))
                            .addComponent(jButton4))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnAddInstructors))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton5)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnLecturessujects)
                                .addGap(26, 26, 26)
                                .addComponent(btnInstructorsSubjects))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)))
                        .addGap(219, 219, 219)
                        .addComponent(btnAddLectures)
                        .addGap(47, 47, 47)
                        .addComponent(btnAddInstrucrors)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddLectures)
                            .addComponent(btnAddInstrucrors)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddLectures1)
                            .addComponent(btnAddInstructors)
                            .addComponent(btnLecturessujects)
                            .addComponent(btnInstructorsSubjects))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acadamic Staff", jPanel4);

        jPanel2.setBackground(new java.awt.Color(137, 50, 255));

        btnAddPostGraduateStudent.setBackground(new java.awt.Color(102, 102, 102));
        btnAddPostGraduateStudent.setText("Add  Student");
        btnAddPostGraduateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPostGraduateStudentActionPerformed(evt);
            }
        });

        btnPostGraduateCourse.setBackground(new java.awt.Color(102, 102, 102));
        btnPostGraduateCourse.setText("Add Course");
        btnPostGraduateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostGraduateCourseActionPerformed(evt);
            }
        });

        btnPostGraduateResult.setBackground(new java.awt.Color(102, 102, 102));
        btnPostGraduateResult.setText("Set Result");
        btnPostGraduateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostGraduateResultActionPerformed(evt);
            }
        });

        btnPostCalGPA.setBackground(new java.awt.Color(102, 102, 102));
        btnPostCalGPA.setText("Cal GPA");
        btnPostCalGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostCalGPAActionPerformed(evt);
            }
        });

        jTextField1.setText("update and Delete");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsmbuniversity/9.jpg"))); // NOI18N

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setText("Update And Delete");

        jButton9.setBackground(new java.awt.Color(204, 204, 255));
        jButton9.setText("Update And Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 204, 255));
        jButton10.setText("Update And Delete");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnAddPostGraduateStudent)
                            .addGap(52, 52, 52)
                            .addComponent(btnPostGraduateCourse)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(btnPostGraduateResult))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jButton10)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                            .addComponent(btnPostCalGPA)
                            .addContainerGap(62, Short.MAX_VALUE)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPostGraduateStudent)
                    .addComponent(btnPostGraduateCourse)
                    .addComponent(btnPostGraduateResult)
                    .addComponent(btnPostCalGPA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(516, 516, 516)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Post Graduate", jPanel2);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsmbuniversity/about-banner.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(188, 188, 188))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostCalGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostCalGPAActionPerformed
        PostCalGPA pcg=new PostCalGPA();
        pcg.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_btnPostCalGPAActionPerformed

    private void btnPostGraduateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostGraduateResultActionPerformed
        AddPostGraduateResult apgr=new AddPostGraduateResult();
        apgr.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnPostGraduateResultActionPerformed

    private void btnPostGraduateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostGraduateCourseActionPerformed
        CoursePostGraduate cpg=new CoursePostGraduate();
        cpg.setVisible(true);

    }//GEN-LAST:event_btnPostGraduateCourseActionPerformed

    private void btnAddPostGraduateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPostGraduateStudentActionPerformed
        AddPostGraduate adpg=new AddPostGraduate();
        adpg.setVisible(true);
    }//GEN-LAST:event_btnAddPostGraduateStudentActionPerformed

    private void btnAddInstructorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInstructorsActionPerformed
        InstructorDetail id=new InstructorDetail();
        id.setVisible(true);
    }//GEN-LAST:event_btnAddInstructorsActionPerformed

    private void AddLectures1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLectures1ActionPerformed
        AddLecturesDetail ald=new AddLecturesDetail();
        ald.setVisible(true);
    }//GEN-LAST:event_AddLectures1ActionPerformed

    private void btnAddInstrucrorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInstrucrorsActionPerformed
        InstructorDetail id=new InstructorDetail();
        id.setVisible(true);
    }//GEN-LAST:event_btnAddInstrucrorsActionPerformed

    private void btnAddLecturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLecturesActionPerformed
        AddLecturesDetail ald=new AddLecturesDetail();
        ald.setVisible(true);
    }//GEN-LAST:event_btnAddLecturesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UndergraduateCourseUpdateDelete ugcup=new UndergraduateCourseUpdateDelete();
        ugcup.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCalGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalGPAActionPerformed
        UnderCalGpa ucgpa=new UnderCalGpa();
        ucgpa.setVisible(true);
    }//GEN-LAST:event_btnCalGPAActionPerformed

    private void btnUnderGraduateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnderGraduateResultActionPerformed
        AddUnderGraduateResult augr=new AddUnderGraduateResult();
        augr.setVisible(true);
    }//GEN-LAST:event_btnUnderGraduateResultActionPerformed

    private void btnUnderGraduateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnderGraduateCourseActionPerformed
        CourseDetail cd=new CourseDetail();
        cd.setVisible(true);
    }//GEN-LAST:event_btnUnderGraduateCourseActionPerformed

    private void btnAddUnderGraduateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUnderGraduateStudentActionPerformed
        AddUnderGraduate adud;
        adud = new AddUnderGraduate();
        adud.setVisible(true);

    }//GEN-LAST:event_btnAddUnderGraduateStudentActionPerformed

    private void btnLecturessujectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturessujectsActionPerformed
        LecturersSubjects ls=new LecturersSubjects();
        ls.setVisible(true);
    }//GEN-LAST:event_btnLecturessujectsActionPerformed

    private void btnInstructorsSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructorsSubjectsActionPerformed
       InstructorSubjectl is=new InstructorSubjectl();
       is.setVisible(true);
    }//GEN-LAST:event_btnInstructorsSubjectsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        PostGraduateCourseUpdateDelete pgcu=new   PostGraduateCourseUpdateDelete();
        pgcu.setVisible(true);
        pgcu.setResizable(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLectures1;
    private javax.swing.JButton btnAddInstrucrors;
    private javax.swing.JButton btnAddInstructors;
    private javax.swing.JButton btnAddLectures;
    private javax.swing.JButton btnAddPostGraduateStudent;
    private javax.swing.JButton btnAddUnderGraduateStudent;
    private javax.swing.JButton btnCalGPA;
    private javax.swing.JButton btnInstructorsSubjects;
    private javax.swing.JButton btnLecturessujects;
    private javax.swing.JButton btnPostCalGPA;
    private javax.swing.JButton btnPostGraduateCourse;
    private javax.swing.JButton btnPostGraduateResult;
    private javax.swing.JButton btnUnderGraduateCourse;
    private javax.swing.JButton btnUnderGraduateResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
